// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v5.29.3
// source: proto/transcode.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Transcode_SendData_FullMethodName = "/transcode.Transcode/SendData"
)

// TranscodeClient is the client API for Transcode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TranscodeClient interface {
	SendData(ctx context.Context, in *SendStreamDataRequest, opts ...grpc.CallOption) (*Result, error)
}

type transcodeClient struct {
	cc grpc.ClientConnInterface
}

func NewTranscodeClient(cc grpc.ClientConnInterface) TranscodeClient {
	return &transcodeClient{cc}
}

func (c *transcodeClient) SendData(ctx context.Context, in *SendStreamDataRequest, opts ...grpc.CallOption) (*Result, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Result)
	err := c.cc.Invoke(ctx, Transcode_SendData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TranscodeServer is the server API for Transcode service.
// All implementations must embed UnimplementedTranscodeServer
// for forward compatibility.
type TranscodeServer interface {
	SendData(context.Context, *SendStreamDataRequest) (*Result, error)
	mustEmbedUnimplementedTranscodeServer()
}

// UnimplementedTranscodeServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTranscodeServer struct{}

func (UnimplementedTranscodeServer) SendData(context.Context, *SendStreamDataRequest) (*Result, error) {
	return nil, status.Error(codes.Unimplemented, "method SendData not implemented")
}
func (UnimplementedTranscodeServer) mustEmbedUnimplementedTranscodeServer() {}
func (UnimplementedTranscodeServer) testEmbeddedByValue()                   {}

// UnsafeTranscodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TranscodeServer will
// result in compilation errors.
type UnsafeTranscodeServer interface {
	mustEmbedUnimplementedTranscodeServer()
}

func RegisterTranscodeServer(s grpc.ServiceRegistrar, srv TranscodeServer) {
	// If the following call panics, it indicates UnimplementedTranscodeServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Transcode_ServiceDesc, srv)
}

func _Transcode_SendData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendStreamDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TranscodeServer).SendData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Transcode_SendData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TranscodeServer).SendData(ctx, req.(*SendStreamDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Transcode_ServiceDesc is the grpc.ServiceDesc for Transcode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Transcode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "transcode.Transcode",
	HandlerType: (*TranscodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendData",
			Handler:    _Transcode_SendData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/transcode.proto",
}
